In [1]:
import spacy
import pandas as pd

In [2]:
nlp = spacy.load("en_core_web_sm")

In [3]:
emma_ja = "emma woodhouse handsome clever and rich with a comfortable home and happy disposition seemed to unite some of the best blessings of existence and had lived nearly twentyone years in the world with very little to distress or vex her she was the youngest of the two daughters of a most affectionate indulgent father and had in consequence of her sisters marriage been mistress of his house from a very early period her mother had died too long ago for her to have more than an indistinct remembrance of her caresses and her place had been supplied by an excellent woman as governess who had fallen little short of a mother in affection sixteen years had miss taylor been in mr woodhouses family less as a governess than a friend very fond of both daughters but particularly of emma between them it was more the intimacy of sisters even before miss taylor had ceased to hold the nominal office of governess the mildness of her temper had hardly allowed her to impose any restraint and the shadow of authority being now long passed away they had been living together as friend and friend very mutually attached and emma doing just what she liked highly esteeming miss taylors judgment but directed chiefly by her own"

In [4]:
doc = nlp(emma_ja)

In [7]:
pos_df = pd.DataFrame.from_records({'token': t.text, 'pos_tag': t.pos_} for t in doc)

In [13]:
pos_df.groupby(['token','pos_tag']).size().reset_index(name= "count").sort_values(by= "count", ascending= False )

         token pos_tag  count
88          of     ADP     14
49         had     AUX      9
54         her    PRON      9
111        the     DET      8
6          and   CCONJ      8
..         ...     ...    ...
43      father    NOUN      1
42      family    NOUN      1
41      fallen    VERB      1
40   existence    NOUN      1
131   youngest     ADJ      1

[132 rows x 3 columns]

In [20]:
pos_df.groupby(['pos_tag'])['token'].count().reset_index(name="count").sort_values(by="count", ascending= False )

   pos_tag  count
6     NOUN     44
1      ADP     28
2      ADV     22
0      ADJ     19
12    VERB     19
5      DET     18
9     PRON     18
3      AUX     16
4    CCONJ     11
10   PROPN      8
8     PART      5
7      NUM      3
11   SCONJ      3

In [22]:
nouns = pos_df[pos_df["pos_tag"] == "NOUN"]
nouns

           token pos_tag
9           home    NOUN
12   disposition    NOUN
20     blessings    NOUN
22     existence    NOUN
28         years    NOUN
31         world    NOUN
36      distress    NOUN
38           vex    NOUN
47     daughters    NOUN
53        father    NOUN
57   consequence    NOUN
60       sisters    NOUN
61      marriage    NOUN
63      mistress    NOUN
66         house    NOUN
71        period    NOUN
73        mother    NOUN
87   remembrance    NOUN
90      caresses    NOUN
93         place    NOUN
100        woman    NOUN
102    governess    NOUN
110       mother    NOUN
112    affection    NOUN
114        years    NOUN
122       family    NOUN
126    governess    NOUN
129       friend    NOUN
134    daughters    NOUN
138         emma    NOUN
145     intimacy    NOUN
147      sisters    NOUN
158       office    NOUN
160    governess    NOUN
162     mildness    NOUN
165       temper    NOUN
173    restraint    NOUN
176       shadow    NOUN
178    authority    NOUN
190       friend    NOUN
192       friend    NOUN
197         emma    NOUN
206      taylors    NOUN
207     judgment    NOUN