In [2]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
data = pd.DataFrame([("i love spending time with my friends and family", "positive"),
("that was the best meal i've ever had in my life", "positive"),
("i feel so grateful for everything i have in my life", "positive"),
("i received a promotion at work and i couldn't be happier", "positive"),
("watching a beautiful sunset always fills me with joy", "positive"),
("my partner surprised me with a thoughtful gift and it made my day", "positive"),
("i am so proud of my daughter for graduating with honors", "positive"),
("listening to my favorite music always puts me in a good mood", "positive"),
("i love the feeling of accomplishment after completing a challenging task", "positive"),
("i am excited to go on vacation next week", "positive"),
("i feel so overwhelmed with work and responsibilities", "negative"),
("the traffic during my commute is always so frustrating", "negative"),
("i received a parking ticket and it ruined my day", "negative"),
("i got into an argument with my partner and we're not speaking", "negative"),
("i have a headache and i feel terrible", "negative"),
("i received a rejection letter for the job i really wanted", "negative"),
("my car broke down and it's going to be expensive to fix", "negative"),
("i'm feeling sad because i miss my friends who live far away", "negative"),
("i'm frustrated because i can't seem to make progress on my project", "negative"),
("i'm disappointed because my team lost the game", "negative")], columns=['text', 'sentiment'])

In [4]:
data = data.sample(frac=1).reset_index(drop = True)
data.head()

                                                text sentiment
0   i received a parking ticket and it ruined my day  negative
1  i feel so grateful for everything i have in my...  positive
2  i received a promotion at work and i couldn't ...  positive
3  i got into an argument with my partner and we'...  negative
4  i am so proud of my daughter for graduating wi...  positive

In [5]:
vectorizer = CountVectorizer()
convert_fit = vectorizer.fit_transform(data["text"])
bag_of_words = pd.DataFrame(convert_fit.toarray(), columns= vectorizer.get_feature_names_out())
bag_of_words.head()

,accomplishment,after,always,am,an,and,argument,at,away,be,...,vacation,ve,wanted,was,watching,we,week,who,with,work
0,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,1,0,1,0,1,...,0,0,0,0,0,0,0,0,0,1
3,0,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,1,0,0,1,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [6]:
X_train, X_test, y_train, y_test = train_test_split(bag_of_words, data["sentiment"], test_size=0.3, random_state=7)

In [9]:
model  = MultinomialNB()

In [10]:
model.fit(X_train, y_train)

MultinomialNB()

In [12]:
acc = accuracy_score(y_test, model.predict(X_test)) * 100
acc

66.66666666666666